### ISSUE TITLE
Missing license info

### ISSUE THREAD

**Issue by dwrobel** [borco/plantumlqeditor#15]
I'm trying to package plantumlqeditor for Fedora, however some of the files seems to have missing license info. Complete list of files can be found in review[[1]](https://bugzilla.redhat.com/show_bug.cgi?id=1427085#c4).

Could you please consider to add missing license info to those files?

[1] https://bugzilla.redhat.com/show_bug.cgi?id=1427085#c4

**Comment by ghost** [comment]
done.
